/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'alexeybuzdin' at '11/12/13 3:11 PM' with Gradle 1.7
 *
 * @author alexeybuzdin, @date 11/12/13 3:11 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
